# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  client-build:

    runs-on: ubuntu-latest
    env:
      working-dir: ./

    steps:
    - uses: actions/checkout@v2
    - name: Client use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn
      working-directory: ${{ env.working-dir }}
    - run: yarn build
      working-directory: ${{ env.working-dir }}
      env:
        CI: true
